#!/usr/bin/env bash
#configure nginx server to listen for port 80
#it's replacing the line in the config filein which it says 8080 to 80
#Thanks New me
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
