#!/usr/bin/env bash
#this script prints best school using while loop ten times and Hi
i=1
while [[ $i -le 10 ]]
do
    if [ $i = 9 ]; then
        echo "Hi"
        i=$((i+1))
        continue
    fi
    echo "Best School"
    i=$((i+1))
done
