#!/usr/bin/env bash
#this script prints best school using while loop ten times
i="1"
while [[ $i -le 10 ]]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
