#!/usr/bin/env bash
#change your home ip
# facebook 8.8.8.8
# localhost 127.0.0.2
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
